In [1]:
import tensorflow as tf

In [2]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'E:\\Anaconda\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [3]:
#Intitialization of Tensors
x = tf.constant(4, shape = (1,1), dtype = tf.int64)
print(x)

tf.Tensor([[4]], shape=(1, 1), dtype=int64)


In [4]:
x = tf.constant([[1,2,3], [4,5,6]], shape = (3,2))
print(x)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [6]:
x = tf.ones(shape = (5,5), dtype = tf.int64)
print(x)

tf.Tensor(
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]], shape=(5, 5), dtype=int64)


In [7]:
x = tf.zeros((4,4), dtype = tf.int64)
print(x)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(4, 4), dtype=int64)


In [8]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [9]:
x = tf.random.normal((3,3), mean = 0, stddev = 1)
print(x)

tf.Tensor(
[[ 1.6506687  -2.109423   -1.3962345 ]
 [-0.7634407   0.23373425 -1.3967476 ]
 [-1.9738145  -1.3692828   0.9849048 ]], shape=(3, 3), dtype=float32)


In [16]:
x = tf.random.uniform((3,3), minval = 0, maxval = 1 )
print(x)

tf.Tensor(
[[0.09952724 0.7161013  0.5961286 ]
 [0.9448985  0.20621645 0.00531912]
 [0.23502982 0.34811652 0.3283391 ]], shape=(3, 3), dtype=float32)


In [17]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [18]:
x = tf.range(start = 0, limit = 11, delta = 2)
print(x)

tf.Tensor([ 0  2  4  6  8 10], shape=(6,), dtype=int32)


In [19]:
x = tf.cast(x, dtype = tf.float64)
print(x)

tf.Tensor([ 0.  2.  4.  6.  8. 10.], shape=(6,), dtype=float64)


In [6]:
x = tf.constant([[1,2,3], [4,5,6]])
y = tf.constant([4,5,6])
a = tf.add(x,y)
s = tf.subtract(x,y)
d = tf.divide(x,y)
m = tf.multiply(x,y)
t = tf.reduce_sum(x*y, axis = 1)
print(a)
print(s)
print(d)
print(m)
print(t)
print(x)

tf.Tensor(
[[ 5  7  9]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-3 -3 -3]
 [ 0  0  0]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0.25 0.4  0.5 ]
 [1.   1.   1.  ]], shape=(2, 3), dtype=float64)
tf.Tensor(
[[ 4 10 18]
 [16 25 36]], shape=(2, 3), dtype=int32)
tf.Tensor([32 77], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [36]:
z = x**5
print(z)

tf.Tensor(
[[   1   32  243]
 [1024 3125 7776]], shape=(2, 3), dtype=int32)


In [7]:
x = tf.random.normal((1,5))
y = tf.random.normal((5,10))
z = x @ y
print(x)
print(z)

tf.Tensor([[ 0.35159594 -0.25772667  0.25194302 -1.0026737   0.81180555]], shape=(1, 5), dtype=float32)
tf.Tensor(
[[-0.98035616 -0.14598584 -0.6035484  -0.26627898  0.45615554 -3.3332214
   0.6892321   0.6135422   0.59144807 -2.9027815 ]], shape=(1, 10), dtype=float32)


In [51]:
x = tf.constant([1,2,3,4,5,6,7,8,9])
print(x[:])
print(x[1:])
print(x[::-1])
print(x[::2])
indices = tf.constant([0,3])
x_in = tf.gather(x, indices)
print(x_in)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor([2 3 4 5 6 7 8 9], shape=(8,), dtype=int32)
tf.Tensor([9 8 7 6 5 4 3 2 1], shape=(9,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1 4], shape=(2,), dtype=int32)


In [54]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
print(x[0,:])
print(x[:,:])
print(x[1,1])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [63]:
x = tf.random.normal((1,9))
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[[ 0.63074917  0.06714085 -1.8509215 ]
 [-1.0622646  -0.42228335  0.93900007]
 [-0.6324736   0.46302816  1.1456529 ]], shape=(3, 3), dtype=float32)


In [64]:
x = tf.transpose(x, perm = [1,0])
print(x)

tf.Tensor(
[[ 0.63074917 -1.0622646  -0.6324736 ]
 [ 0.06714085 -0.42228335  0.46302816]
 [-1.8509215   0.93900007  1.1456529 ]], shape=(3, 3), dtype=float32)


In [65]:
x = tf.transpose(x)
print(x)

tf.Tensor(
[[ 0.63074917  0.06714085 -1.8509215 ]
 [-1.0622646  -0.42228335  0.93900007]
 [-0.6324736   0.46302816  1.1456529 ]], shape=(3, 3), dtype=float32)
